//
//  Currency.swift
//  Buy?
//
//  Created by Xizhen Yang on 1/21/19.
//  Copyright © 2019 Churong Zhang. All rights reserved.
//

import Foundation


class Currency
{
    let currencyArray = ["USD", "CNY","BTC","AFN", "ALL", "DZD", "AOA", "ARS", "AMD", "AWG", "AUD", "AZN", "BSD", "BHD", "BDT", "BBD", "BYR", "BZD", "BMD", "BTN", "BTC", "BOB", "BAM", "BWP", "BRL", "GBP", "BND", "BGN", "BIF", "KHR", "CAD", "CVE", "KYD", "XOF", "XAF", "XPF", "CLP", "CLF", "CNY", "COP", "KMF", "CDF", "CRC", "HRK", "CUC", "CUP", "CZK", "DKK", "DJF", "DOP", "XCD", "EGP", "ERN", "ETB", "EUR", "FKP", "FJD", "GMD", "GEL", "GHS", "GIP", "XAU", "GTQ", "GGP", "GNF", "GYD", "HTG", "HNL", "HKD", "HUF", "ISK", "INR", "IDR", "IRR", "IQD", "ILS", "JMD", "JPY", "JEP", "JOD", "KZT", "KES", "KWD", "KGS", "LAK", "LVL", "LBP", "LSL", "LRD", "LYD", "LTL", "MOP", "MKD", "MGA", "MWK", "MYR", "MVR", "IMP", "MRO", "MUR", "MXN", "MDL", "MNT", "MAD", "MZN", "MMK", "NAD", "NPR", "ANG", "TWD", "NZD", "NIO", "NGN", "KPW", "NOK", "OMR", "PKR", "PAB", "PGK", "PYG", "PEN", "PHP", "PLN", "QAR", "RON", "RUB", "RWF", "SHP", "SVC", "WST", "STD", "SAR", "RSD", "SCR", "SLL", "XAG", "SGD", "SBD", "SOS", "ZAR", "KRW", "XDR", "LKR", "SDG", "SRD", "SZL", "SEK", "CHF", "SYP", "TJS", "TZS", "THB", "TOP", "TTD", "TND", "TRY", "TMT", "UGX", "UAH", "AED", "USD", "UYU", "UZS", "VUV", "VEF", "VND", "YER", "ZMW", "ZMK", "ZWL"]
    //["AUD", "BRL","CAD","CNY","EUR","GBP","HKD","IDR","ILS","INR","JPY","MXN","NOK","NZD","PLN","RON","RUB","SEK","SGD","USD","ZAR"]
    let currencyName = [ "US Dollar", "人民币 Chinese Yuan", "Bitcoin",
                            "Afghan Afghani",
                        "Albanian Lek",
                        "Algerian Dinar",
                        "Angolan Kwanza",
                        "Argentine Peso",
                        "Armenian Dram",
                        "Aruban Florin",
                        "Australian Dollar",
                        "Azerbaijani Manat",
                        "Bahamian Dollar",
                        "Bahraini Dinar",
                        "Bangladeshi Taka",
                        "Barbadian Dollar",
                        "Belarusian Ruble",
                        "Belize Dollar",
                        "Bermudan Dollar",
                        "Bhutanese Ngultrum",
                        "Bitcoin",
                        "Bolivian Boliviano",
                        "Bosnia-Herzegovina Convertible Mark",
                        "Botswanan Pula",
                        "Brazilian Real",
                        "British Pound Sterling",
                        "Brunei Dollar",
                        "Bulgarian Lev",
                        "Burundian Franc",
                        "Cambodian Riel",
                        "Canadian Dollar",
                        "Cape Verdean Escudo",
                        "Cayman Islands Dollar",
                        "CFA Franc BCEAO",
                        "CFA Franc BEAC",
                        "CFP Franc",
                        "Chilean Peso",
                        "Chilean Unit of Account (UF)",
                        "人民币 Chinese Yuan",
                        "Colombian Peso",
                        "Comorian Franc",
                        "Congolese Franc",
                        "Costa Rican Colón",
                        "Croatian Kuna",
                        "Cuban Convertible Peso",
                        "Cuban Peso",
                        "Czech Republic Koruna",
                        "Danish Krone",
                        "Djiboutian Franc",
                        "Dominican Peso",
                        "East Caribbean Dollar",
                        "Egyptian Pound",
                        "Eritrean Nakfa",
                        "Ethiopian Birr",
                        "Euro",
                        "Falkland Islands Pound",
                        "Fijian Dollar",
                        "Gambian Dalasi",
                        "Georgian Lari",
                        "Ghanaian Cedi",
                        "Gibraltar Pound",
                        "Gold (troy ounce)",
                        "Guatemalan Quetzal",
                        "Guernsey Pound",
                        "Guinean Franc",
                        "Guyanaese Dollar",
                        "Haitian Gourde",
                        "Honduran Lempira",
                        "Hong Kong Dollar",
                        "Hungarian Forint",
                        "Icelandic Króna",
                        "Indian Rupee",
                        "Indonesian Rupiah",
                        "Iranian Rial",
                        "Iraqi Dinar",
                        "Israeli New Sheqel",
                        "Jamaican Dollar",
                        "Japanese Yen",
                        "Jersey Pound",
                        "Jordanian Dinar",
                        "Kazakhstani Tenge",
                        "Kenyan Shilling",
                        "Kuwaiti Dinar",
                        "Kyrgystani Som",
                        "Laotian Kip",
                        "Latvian Lats",
                        "Lebanese Pound",
                        "Lesotho Loti",
                        "Liberian Dollar",
                        "Libyan Dinar",
                        "Lithuanian Litas",
                        "Macanese Pataca",
                        "Macedonian Denar",
                        "Malagasy Ariary",
                        "Malawian Kwacha",
                        "Malaysian Ringgit",
                        "Maldivian Rufiyaa",
                        "Manx pound",
                        "Mauritanian Ouguiya",
                        "Mauritian Rupee",
                        "Mexican Peso",
                        "Moldovan Leu",
                        "Mongolian Tugrik",
                        "Moroccan Dirham",
                        "Mozambican Metical",
                        "Myanma Kyat",
                        "Namibian Dollar",
                        "Nepalese Rupee",
                        "Netherlands Antillean Guilder",
                        "New Taiwan Dollar",
                        "New Zealand Dollar",
                        "Nicaraguan Córdoba",
                        "Nigerian Naira",
                        "North Korean Won",
                        "Norwegian Krone",
                        "Omani Rial",
                        "Pakistani Rupee",
                        "Panamanian Balboa",
                        "Papua New Guinean Kina",
                        "Paraguayan Guarani",
                        "Peruvian Nuevo Sol",
                        "Philippine Peso",
                        "Polish Zloty",
                        "Qatari Rial",
                        "Romanian Leu",
                        "Russian Ruble",
                        "Rwandan Franc",
                        "Saint Helena Pound",
                        "Salvadoran Colón",
                        "Samoan Tala",
                        "São Tomé and Príncipe Dobra",
                        "Saudi Riyal",
                        "Serbian Dinar",
                        "Seychellois Rupee",
                        "Sierra Leonean Leone",
                        "Silver (troy ounce)",
                        "Singapore Dollar",
                        "Solomon Islands Dollar",
                        "Somali Shilling",
                        "South African Rand",
                        "South Korean Won",
                        "Special Drawing Rights",
                        "Sri Lankan Rupee",
                        "Sudanese Pound",
                        "Surinamese Dollar",
                        "Swazi Lilangeni",
                        "Swedish Krona",
                        "Swiss Franc",
                        "Syrian Pound",
                        "Tajikistani Somoni",
                        "Tanzanian Shilling",
                        "Thai Baht",
                        "Tongan Paʻanga",
                        "Trinidad and Tobago Dollar",
                        "Tunisian Dinar",
                        "Turkish Lira",
                        "Turkmenistani Manat",
                        "Ugandan Shilling",
                        "Ukrainian Hryvnia",
                        "United Arab Emirates Dirham",
                        "United States Dollar",
                        "Uruguayan Peso",
                        "Uzbekistan Som",
                        "Vanuatu Vatu",
                        "Venezuelan Bolívar Fuerte",
                        "Vietnamese Dong",
                        "Yemeni Rial",
                        "Zambian Kwacha",
                        "Zambian Kwacha (pre-2013)",
                        "Zimbabwean Dollar"]
    
  
    
    
    
   
}
